//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Initiative_Delivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Data_Initiative_Delivery()
        {
            this.Data_Initiative_Delivery_Line = new HashSet<Data_Initiative_Delivery_Line>();
        }
    
        public int initiative_delivery_id { get; set; }
        public string tpb_id { get; set; }
        public string materials { get; set; }
        public string account { get; set; }
        public Nullable<System.DateTime> approval_date { get; set; }
        public Nullable<System.DateTime> tpa_delivery_date { get; set; }
        public string tpa_delivery_status { get; set; }
        public Nullable<int> tpa_delivery_status_id { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string deleted_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Data_Initiative_Delivery_Line> Data_Initiative_Delivery_Line { get; set; }
    }
}
