//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Initiative
    {
        public int initiative_id { get; set; }
        public string tpb_id { get; set; }
        public string year { get; set; }
        public string month { get; set; }
        public string channel { get; set; }
        public string agency { get; set; }
        public string initiative_type { get; set; }
        public string initiative_sub_type { get; set; }
        public string category { get; set; }
        public string division { get; set; }
        public string brand { get; set; }
        public string initiative_title { get; set; }
        public string materials { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string account { get; set; }
        public Nullable<System.DateTime> sell_in_date { get; set; }
        public Nullable<int> account_allocation { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
        public string modified_by { get; set; }
    }
}
