//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Initiative_Branch
    {
        public int initiative_branch_id { get; set; }
        public string tpb_id { get; set; }
        public string materials { get; set; }
        public string account { get; set; }
        public Nullable<int> branch_apd_id { get; set; }
        public Nullable<int> branch_delivery_status_id { get; set; }
        public Nullable<System.DateTime> branch_delivery_date { get; set; }
        public string branch_delivery_status { get; set; }
        public Nullable<int> branch_allocation { get; set; }
        public Nullable<int> total_bundled { get; set; }
        public string percent_bundled { get; set; }
        public Nullable<System.DateTime> start_of_implem { get; set; }
        public string implem_status { get; set; }
        public Nullable<int> implem_status_id { get; set; }
        public string implem_issue { get; set; }
        public Nullable<int> implem_issue_id { get; set; }
        public Nullable<System.DateTime> date_of_completion { get; set; }
        public Nullable<int> total_offtake { get; set; }
        public string percent_offtake { get; set; }
        public Nullable<int> ending_inventory { get; set; }
        public string offtake_analysis { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string deleted_by { get; set; }
    
        public virtual Ref_Branch_APD Ref_Branch_APD { get; set; }
    }
}
