//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Initiative_Branch_Line
    {
        public int initiative_branch_line_id { get; set; }
        public Nullable<int> initiative_branch_id { get; set; }
        public Nullable<int> week_no { get; set; }
        public Nullable<int> month_no { get; set; }
        public Nullable<int> branch_delivered_qty { get; set; }
        public Nullable<int> actual_bundled { get; set; }
        public string implem_issue { get; set; }
        public Nullable<int> implem_issue_id { get; set; }
        public Nullable<int> actual_offtake { get; set; }
        public string status { get; set; }
        public Nullable<bool> is_approved { get; set; }
        public Nullable<System.DateTime> approved_at { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string deleted_by { get; set; }
        public string source { get; set; }
    
        public virtual Data_Initiative_Branch_File Data_Initiative_Branch_File { get; set; }
    }
}
