//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Web_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TPA_ImplemEntities : DbContext
    {
        public TPA_ImplemEntities()
            : base("name=TPA_ImplemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Data_Branch_Allocation> Data_Branch_Allocation { get; set; }
        public virtual DbSet<Data_Initiative> Data_Initiative { get; set; }
        public virtual DbSet<Data_Offtake> Data_Offtake { get; set; }
        public virtual DbSet<Data_TPA_Delivery> Data_TPA_Delivery { get; set; }
        public virtual DbSet<Ref_Branch_APD> Ref_Branch_APD { get; set; }
        public virtual DbSet<Ref_Branch_Assignment> Ref_Branch_Assignment { get; set; }
        public virtual DbSet<Ref_Implem_Status> Ref_Implem_Status { get; set; }
        public virtual DbSet<Ref_User> Ref_User { get; set; }
        public virtual DbSet<Ref_User_Profile> Ref_User_Profile { get; set; }
        public virtual DbSet<Data_Branch_Delivery> Data_Branch_Delivery { get; set; }
        public virtual DbSet<Data_Installation_Issue> Data_Installation_Issue { get; set; }
        public virtual DbSet<Ref_Branch_Delivery_Status> Ref_Branch_Delivery_Status { get; set; }
        public virtual DbSet<Ref_Implem_Issue> Ref_Implem_Issue { get; set; }
        public virtual DbSet<Ref_TPA_Calendar> Ref_TPA_Calendar { get; set; }
        public virtual DbSet<Ref_TPA_Delivery_Status> Ref_TPA_Delivery_Status { get; set; }
        public virtual DbSet<Data_Installation> Data_Installation { get; set; }
    }
}
