//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_Branch_Assignment
    {
        public int branch_assignment_id { get; set; }
        public Nullable<int> branch_apd_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string deleted_by { get; set; }
    
        public virtual Ref_Branch_APD Ref_Branch_APD { get; set; }
        public virtual Ref_User Ref_User { get; set; }
    }
}
