//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_Branch_APD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ref_Branch_APD()
        {
            this.Ref_Branch_Assignment = new HashSet<Ref_Branch_Assignment>();
        }
    
        public int branch_apd_id { get; set; }
        public string agency { get; set; }
        public string channel { get; set; }
        public string area { get; set; }
        public string cds { get; set; }
        public string distributor { get; set; }
        public string account { get; set; }
        public string branch_name { get; set; }
        public string branch_code { get; set; }
        public string address { get; set; }
        public string sfa_id { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string classification { get; set; }
        public string team_lead { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ref_Branch_Assignment> Ref_Branch_Assignment { get; set; }
    }
}
