//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_Branch_Assignment
    {
        public int ID { get; set; }
        public Nullable<int> Branch_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public string Created_By { get; set; }
    
        public virtual Ref_Branch_APD Ref_Branch_APD { get; set; }
        public virtual Ref_User Ref_User { get; set; }
    }
}
