//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_Branch_APD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ref_Branch_APD()
        {
            this.Ref_Branch_Assignment = new HashSet<Ref_Branch_Assignment>();
        }
    
        public int ID { get; set; }
        public string Agency { get; set; }
        public string Channel { get; set; }
        public string Area { get; set; }
        public string CDS { get; set; }
        public string Distributor { get; set; }
        public string AccountGroup { get; set; }
        public string BranchName { get; set; }
        public string BranchCode { get; set; }
        public string Address { get; set; }
        public string SFA_ID { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Classification { get; set; }
        public string TeamLead { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ref_Branch_Assignment> Ref_Branch_Assignment { get; set; }
    }
}
