//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ref_User()
        {
            this.Ref_Branch_Assignment = new HashSet<Ref_Branch_Assignment>();
        }
    
        public int user_id { get; set; }
        public string username { get; set; }
        public string hash { get; set; }
        public byte[] salt { get; set; }
        public Nullable<int> user_profile_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ref_Branch_Assignment> Ref_Branch_Assignment { get; set; }
        public virtual Ref_User_Profile Ref_User_Profile { get; set; }
    }
}
