//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Source_Data_Mobile_Attrib_1
    {
        public string initiative_id { get; set; }
        public string material { get; set; }
        public string attachment_id { get; set; }
        public string attachment_file_name { get; set; }
        public byte[] image { get; set; }
        public string branch_id { get; set; }
        public Nullable<int> attachment_type { get; set; }
        public byte[] attachment { get; set; }
        public Nullable<int> week_no { get; set; }
        public Nullable<int> month_no { get; set; }
        public string captured_by { get; set; }
        public string captured_date { get; set; }
        public string sync_at { get; set; }
        public Nullable<System.DateTime> pulled_at { get; set; }
        public int source_data_mobile_attrib_1_id { get; set; }
    }
}
